#Autocomplete List Class Manim Python Add
#C:\Program Files (x86)\Notepad++\autoCompletion\python.xml
#C:\Program Files\Notepad++\autoCompletion\python.xml
TracedPath
Axes
ComplexPlane
CoordinateSystem
NumberPlane
ThreeDAxes
FullScreenFadeRectangle
FullScreenRectangle
PictureInPictureFrame
ScreenRectangle
FunctionGraph
ParametricFunction
Angle
AnnotationDot
Arc
ArcBetweenPoints
ArcPolygon
ArcPolygonFromArcs
Arrow
ArrowCircleFilledTip
ArrowCircleTip
ArrowSquareFilledTip
ArrowSquareTip
ArrowTip
ArrowTriangleFilledTip
ArrowTriangleTip
Circle 
CubicBezier
CurvedArrow
Cutout
DashedLine
Dot
Elbow
Ellipse
LabeledDot
Line
Polygon
Rectangle
RegularPolygon
RoundedRectangle
Sector
SmallDot
Square 
TangentLine
TipableVMobject
Triangle
Vector
Graph
ManimBanner
DecimalMatrix
IntegerMatrix
Matrix  
MobjectMatrix
Mobject
Group
Mobject
NumberLine
UnitInterval
DecimalNumber
Integer
Variable
BarChart
SampleSpace
BackgroundRectangle
Cross
SurroundingRectangle
Underline
Arrow3D
Cone
Cube
Cylinder
Dot3D
Line3D
ParametricSurface
Prism
Sphere
ThreeDVMobject
Torus
ComplexValueTracker
ExponentialValueTracker
ValueTracker
AnimatedStreamLines
ShowPassingFlashWithThinningStrokeWidth
StreamLines
Brace  
BraceBetweenPoints
BraceLabel
BraceText
Code
SVGPathMobject
VMobjectFromSVGPathstring
SVGMobject
AbstractImageMobject
ImageMobject
ImageMobjectFromCamera
Mobject1D
Mobject2D
PGroup
PMobject
Point
PointCloudDot
CurvesAsSubmobjects
DashedVMobject
VDict
VGroup
VMobject
VectorizedPoint
SceneFileWriter
SpecialThreeDScene
ThreeDScene
LinearTransformationScene
VectorScene
ZoomedScene
GraphScene
MovingCameraScene
ReconfigurableScene
SampleSpaceScene
Scene
Animation
Wait
AnimationGroup
LaggedStart
LaggedStartMap
Succession
AddTextLetterByLetter
AddTextWordByWord
Create
DrawBorderThenFill
ShowCreation
ShowPartial
ShowSubmobjectsOneByOne
Uncreate
Unwrite
FadeIn
FadeInFrom
FadeInFromLarge
FadeInFromPoint
FadeOut
FadeOutAndShift
FadeOutToPoint
VFadeIn
VFadeInThenOut
VFadeOut
GrowArrow
GrowFromCenter
GrowFromEdge
GrowFromPoint
SpinInFromNothing
AnimationOnSurroundingRectangle
ApplyWave
CircleIndicate
Flash
FocusOn
Indicate
ShowCreationThenDestruction
ShowCreationThenDestructionAround
ShowCreationThenFadeAround
ShowCreationThenFadeOut
ShowPassingFlash
ShowPassingFlashAround
TurnInsideOut
WiggleOutThenIn
ComplexHomotopy
Homotopy
MoveAlongPath
PhaseFlow
SmoothedVectorizedHomotopy
ChangeDecimalToValue
ChangingDecimal
Rotate
Rotating
ApplyComplexFunction
ApplyFunction
ApplyMatrix
ApplyMethod
ApplyPointwiseFunction
ApplyPointwiseFunctionToCenter
ClockwiseTransform
CounterclockwiseTransform
CyclicReplace
FadeToColor
FadeTransform
FadeTransformPieces
MoveToTarget
ReplacementTransform
Restore
ScaleInPlace
ShrinkToCenter
Swap
Transform
TransformAnimations
TransformFromCopy
TransformMatchingAbstractBase
TransformMatchingShapes
TransformMatchingTex
MaintainPositionRelativeTo
UpdateFromAlphaFunc
UpdateFromFunc
BackgroundColoredVMobjectDisplayer
Camera
MappingCamera
OldMultiCamera
SplitScreenCamera
CameraFrame
MovingCamera
MultiCamera
ThreeDCamera
ManimConfig
ManimFrame
JSONFormatter
Colors
DictAsObject
CustomEncoder
ManimMagic
TexTemplate
TexTemplateFromFile
TexFontTemplates
TexTemplateLibrary
Container

